### ISSUE TITLE
The data file for Mimic dataset has not been uploaded

### ISSUE THREAD

**Issue by qzzdd** [safe-graph/RioGNN#1]
I am very curious about the novel dataset Mimic, and want to see the powerful performance of RioGNN on it. Could you please upload the mimic.mat file to the github?

**Comment by qzzdd** [comment]
Thanks very much!

**Comment by qzzdd** [comment]
The git-lfs warns " This repository is over its data quota." I can't download the zip file, so could you please send again through e-mail? My e-mail address is "**qinzidi16@mails.ucas.ac.cn**". Thanks very much!

**Comment by YingtongDou** [comment]
We have updated the LFS storage and you can download the mimic dataset via cloning the entire repo using the following command:

git lfs ***@***.***:safe-graph/RioGNN.git

Best,
Yingtong
